---
title: "Temperate phage DDE"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r,echo=FALSE}
pastvalue=function(dyno,lag){

tinc=0.01
bfl=4000

maxlag=(bfl-1)*tinc
p=0

if(lag>maxlag){
if(p==bfl) midpnt=1 else midpnt=p+1
past=hisy[midpnt,dyno]}

else

{
dispnt=floor((lag/tinc)+0.5)
disp=(dispnt*tinc-lag)/tinc

A=0.5*disp*(disp-1)
B=(1-disp^2)
C=0.5*disp*(disp+1)

if (dispnt>p) midpnt=p+dispnt else midpnt=bfl+p-dispnt

if(midpnt==1) leftpnt=bfl else leftpnt=midpnt-1

if(midpnt==bfl) rightpnt=1 else rightpnt=midpnt+1

R=hisy[rightpnt,dyno]
L=hisy[leftpnt,dyno]
M=hisy[midpnt,dyno]

past=A*L+B*M+C*R
}

past}
```

```{r}
nvar=4

r=0.0179
rl=0.0179

K=10^9

mus=7.8*10^-6
mul=7.8*10^-6
mui=7.8*10^-6
muv=5.1*10^-3

beta=10^-8
alpha=0.0316
gamma=50

f=0.1
ee=2.56*10^-7

Tat = 1/alpha
TLt = sqrt(10*100)

y=array(dim=(nvar))

derivs<-function(x,y){

  S_TLt = pastvalue(1, TLt)
  V_TLt = pastvalue(4, TLt)

  S_Tat = pastvalue(1, Tat)
  V_Tat = pastvalue(4, Tat)
  L_Tat = pastvalue(2, Tat)

  survL = exp(-mus * TLt)
  survI = exp(-mui * Tat)

  yx[1]=-beta*y[1]*y[4]-mus*y[1]+r*y[1]*(1-(y[1]+y[2]+y[3])/K)
  yx[2]=f*beta*S_TLt*V_TLt*survL - (mul+ee)*y[2] + rl*y[2]*(1-(y[1]+y[2]+y[3])/K)
  yx[3]=(1-f)*beta*y[1]*y[4] + ee*y[2] - mui*y[3] - ((1-f)*beta*S_Tat*V_Tat + ee*L_Tat)*survI
  yx[4]=gamma*((1-f)*beta*S_Tat*V_Tat + ee*L_Tat)*survI - muv*y[4]
  yx

}

```

```{r}
y[1]=10^6
y[2]=100
y[3]=0
y[4]=1000

obs=150000
buflen=4000
v=0.0
h=0.01

yt=array(1:nvar)
dyt=array(1:nvar)
dym=array(1:nvar)
yout=array(1:nvar)
yx=array(1:nvar)
eqn=array(1:nvar)

hisy=array(0,dim=c(buflen,nvar))
tmp=array(0,dim=c(buflen,nvar))

 hisy[1:buflen,1] = 10^6
```

```{r}

rk4=function(dydx,y,t,n){
for(jj in	1:n)
	yt[jj]=y[jj]+dydx[jj]*h/2
	dyt=derivs(t+h/2,yt)
for(jj in 1:n)
	yt[jj]=y[jj]+h/2*dyt[jj]
	dym=derivs(t+h/2,yt)
for(jj in 1:n)
	yt[jj]=y[jj]+h*dym[jj]
	dym=dyt+dym
	dyt=derivs(t+h,yt)
for(jj in 1:n)
	yout[jj]=y[jj]+(h/6)*(dydx[jj]+dyt[jj]+2*dym[jj])
	yout
}

```

```{r}
t1=array(1:obs)
x1=array(dim=c(obs,nvar))

for(i in 1:obs){
	eqn=derivs(v,y)
	y=rk4(eqn,y,v,nvar)

        for(ii in 1:buflen){
            for(jj in 1:nvar){
                tmp[ii,jj]=hisy[ii,jj]}}

        for(ii in 2:buflen){
            for(jj in 1:nvar){
                hisy[ii,jj]=tmp[ii-1,jj]}}

            for(jj in 1:nvar) hisy[1,jj]=y[jj]

	v=v+h
	x1[i,]=y
	t1[i]=v}

range(x1[,1])
range(x1[,2])
range(x1[,3])
range(x1[,4])
tail(x1, 1)

plot(seq(0, max(t1), length = 10),
     seq(1, max(pmax(x1, 1)), length = 10),
     bty = "l",
     xlab = "Time (minutes)",
     ylab = "Population density (per mL)",
     main = expression("Temperate phage DDE dynamics - Base A (T"[alpha] * " = 31.65 min, T"[L] * " = 31.62 min)"),
     type = "n", log = "y")

lines(t1, pmax(x1[,1], 1), col = "red",     lwd = 1.5)
lines(t1, pmax(x1[,2], 1), col = "blue",    lwd = 1.5)
lines(t1, pmax(x1[,3], 1), col = "black",   lwd = 1.5)
lines(t1, pmax(x1[,4], 1), col = "magenta", lwd = 1.5)

legend("topright",
       legend = c("Susceptible (S)", "Lysogens (L)", "Infected (I)", "Virions (V)"),
       col    = c("red", "blue", "black", "magenta"),
       lwd    = 1.5,
       bty    = "n")

```
